name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift build -v
        xcodebuild test -project MairoDiary.xcodeproj -scheme MarimoDiary -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.6'
